src:
  targets:
    - index.xml
    - skin.html
    - style.css

skin:
  liststyle:
    options:
      train:
        label: '큼직 한 줄'
        buttonText: '&#9632;'
      album:
        label: '썸네일만'
        buttonText: '&#8862;'
      card:
        label: '썸네일 및 제목'
        buttonText: '&#9635;'
      simple:
        label: '간략 목록'
        buttonText: '&#8863;'
      detailed:
        label: '복잡 목록'
        buttonText: '&#9636;'
    default_base: card
    default:
      # 화면별 기본 스타일
#     index:             # 홈
#     category:          # 카테고리
#     archive:           # 보관함
      tag:      simple   # 태그
      search:   detailed # 검색결과
#     location:          # 지역로그

prod:
  dir: production
