go:
  targets:
    - index.xml
    - skin.html
    - style.css
  out_dir: production

skin:
  liststyle:
    options:
      train:
        label: '큼직 한 줄'
        buttonText: '&#9632;'
      album:
        label: '썸네일만'
        buttonText: '&#8862;'
      card:
        label: '썸네일 및 제목'
        buttonText: '&#9635;'
      simple:
        label: '간략 목록'
        buttonText: '&#8863;'
      detailed:
        label: '복잡 목록'
        buttonText: '&#9636;'
    default_base: card
    default:
      # 화면별 기본 스타일
#     index:             # 홈
#     category:          # 카테고리
#     archive:           # 보관함
      tag:      simple   # 태그
      search:   detailed # 검색결과
#     location:          # 지역로그

  homecover:
    train:
      label: '큼직 한 줄'
      desc: '글목록 옵션의 큼직 한 줄과 같다.'
    card:
      label: '작은 앨범'
      desc: '썸네일 오른쪽왼쪽 번갈아 붙임.'
    bookcover:
      label: '책표지'
      desc: '썸네일로 왕큰 배경 함.'
    widepage:
      label: '책장'
      desc: '책장처럼 넘겨본다.'
