src:
  targets:
    - index.xml
    - skin.html
    - style.css

skin:
  liststyle:
    options:
      train:
        desc: '큼직 한 줄'
        buttonText: '&#9632;'
      album:
        desc: '썸네일만'
        buttonText: '&#8862;'
      card:
        desc: '썸네일 및 제목'
        buttonText: '&#9635;'
      simple:
        desc: '간략 목록'
        buttonText: '&#8863;'
      detailed:
        desc: '복잡 목록'
        buttonText: '&#9636;'
    default: card

prod:
  dir: production
