go:
  targets:
    - index.xml
    - skin.html
    - style.css
  out_dir: production

var:
  defaultColor:
    backCol:       '#FFFFFF'
    baseTextCol:   '#333333'
    listBack:      '#F4F4F4'
    borderCol:     '#DDDDDD'
    frameBack:     '#111144'
    frameFore:     '#FFFFFF'
    pointCol:      '#FF6644'
    bonmunTextCol: '#000000'
    bonmunForm:    '#CCBBAA'
    bonmunActing:  '#66AA00'
    highlight:     '#F0FF40'

headitems:
  - '<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>'

skin:
  fontFamily:
    sans:
      url: 'https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap'
      cssValue: "'Nanum Gothic', sans-serif"
    serif:
      url: 'https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap'
      cssValue: "'Noto Serif KR', serif"
    handwriting:
      url: 'https://fonts.googleapis.com/css2?family=Gaegu&display=swap'
      cssValue: "'Gaegu', cursive"
    monospace:
      url: 'https://fonts.googleapis.com/css2?family=Nanum+Gothic+Coding&display=swap'
      cssValue: "'D2Coding', 'Nanum Gothic Coding', consolas, monospace"
    sticker:
      url: 'https://fonts.googleapis.com/css2?family=Jua&display=swap'
      cssValue: "'Jua', sans-serif"

  liststyle:
    options:
      train:
        label: '큼직 한 줄'
        buttonText: '&#9632;'
      album:
        label: '썸네일만'
        buttonText: '&#8862;'
      card:
        label: '썸네일 및 제목'
        buttonText: '&#9635;'
      postit:
        label: '작은 메모'
        buttonText: '&#8863;'
      detailed:
        label: '복잡 목록'
        buttonText: '&#9636;'
    default_base: card
    default:
      # 화면별 기본 스타일
#     index:             # 홈
#     category:          # 카테고리
#     archive:           # 보관함
      tag:      postit   # 태그
      search:   detailed # 검색결과
#     location:          # 지역로그

  homecover:
    train:
      label: '큼직 한 줄'
      desc: '글목록 옵션의 큼직 한 줄과 같다.'
    card:
      label: '작은 앨범'
      desc: '썸네일 오른쪽왼쪽 번갈아 붙임.'
    bookcover:
      label: '책표지'
      desc: '썸네일로 왕큰 배경 함.'
    widepage:
      label: '책장'
      desc: '책장처럼 넘겨본다.'
# XXX 이원화됨. 애초에 이것들이 소스랑 분리돼 settings에 있을 이유가 있을가?
