src:
  targets:
    - index.xml
    - skin.html
    - style.css

skin:
  liststyle:
    options:
      train:
        desc: '큼직 한 줄'
      album:
        desc: '썸네일만'
      card:
        desc: '썸네일 및 제목'
      simple:
        desc: '간략 목록'
      detailed:
        desc: '복잡 목록'
    default: card

prod:
  dir: production
